### ISSUE TITLE
Edgedriver 117.0.2045.60 Linux/MacOS binaries are not published

### ISSUE THREAD

**Issue by rdelhaise-wiiisdom** [MicrosoftEdge/EdgeWebDriver#119]
Hello, 

For testing purposes, we automated the process for EdgeDriver downloading. We use this [API](https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/LATEST_STABLE) to retrieve the last stable version of the driver. But it's unavailable when we try to get it from this [URL](https://msedgedriver.azureedge.net/117.0.2045.60/edgedriver_mac64.zip). 
After some research, we found that the MacOS/Linux versions are not published in this specific release. 

We do not find anything about that in the release notes. 
So why aren't these binaries being published? Because of a CVE? 

Thank you for your answer.

**Comment by bwalderman** [comment]
Hi @rdelhaise-wiiisdom , the `LATEST_STABLE` API is maintained for backwards compatibility with some systems but we don't recommmend new users depend on this API.

The `LATEST_STABLE` API returns the latest release across *any* operating system. Sometimes, Edge will do partial releases to fix a bug on a single OS. So that release may for example contain a Windows binary, but no MacOS or Linux binaries.

The most robust approach for automation download of the correct driver is to use a 3rd party tool like [WebDriverManager](https://bonigarcia.dev/webdrivermanager/) or the new [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) which is built into recent versions of Selenium 4.
