### ISSUE TITLE
Test IE mode in Microsoft Edge with Internet Explorer Driver

### ISSUE THREAD

**Issue by AradhanaJamwal** [MicrosoftEdge/EdgeWebDriver#13]
As per the [Microsoft Blog](https://blogs.windows.com/msedgedev/2022/02/01/test-ie-mode-in-microsoft-edge-internet-explorer-driver/), IE driver 4.0.0 or later binding is needed for automating the application in IE compatibility mode in Edge.

To replicate the environment (After June 15, when there will be no Internet explorer) I just uninstalled the Internet Explorer from my system ) and did little POC on automating the "IE compatibility" supported application using the documentation provided in above link . I found that my IE mode supporting app was not launching and following error was encountered:

"Internet Explorer can't be found. You need to re-install or re-enable Internet Explorer" 

My question here is :

After June 15 once IE will get sunset, would it be feasible to automate the application supporting "IE compatibility mode" using IE driver as stated in above documentation?

**Comment by zoherghadyali** [comment]
Hi Aradhana! Thank you for sending us your feedback. Instead of uninstalling Internet Explorer 11, can you instead follow the steps here: [Disable Internet Explorer 11](https://docs.microsoft.com/deployedge/edge-ie-disable-ie11)?

We highly recommend applying the [Disable IE policy](https://docs.microsoft.com/deployedge/edge-ie-disable-ie11) before June 15, 2022 so that you can control the date the IE desktop app is disabled. Applying this policy will not affect IE mode functionality whereas uninstalling IE does affect IE mode functionality. Please give that a try and let us know how it goes!
