### ISSUE TITLE
Is Edge WebDriver open source?

### ISSUE THREAD

**Issue by 93null** [MicrosoftEdge/EdgeWebDriver#18]
I can't find the source code anywhere, so I assume it's not, but I thought I'd check. Thanks!

**Comment by zoherghadyali** [comment]
Hi @93null! Thank you for your feedback! Since the Microsoft Edge browser is based on the Chromium open-source project, our source code for Microsoft Edge WebDriver is shared with Chromium's ChromeDriver [here](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/chromedriver). You can contribute to the project just like any other Chromium contributor. We're also happy to take issues from this repo to the Chromium project as needed!
