### ISSUE TITLE
Automation Testing Edge Webview2 with Selenium Python - Throwing error chrome not reachable

### ISSUE THREAD

**Issue by MohammedAfrozKhan** [MicrosoftEdge/EdgeWebDriver#35]
i am trying to run the WebView2 (config.exe) using the following code :

```
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.edge.options import Options
import os

service = Service(os.getcwd() + '/msedgedriver.exe',verbose = True)
options = Options()
options.add_argument('--remote-debugging-port=32001')
options.add_argument("--no-sandbox")
options.add_argument("--headless")
options.add_argument("--disable-gpu")
options.add_argument("--disable-extensions")
options.add_argument("--disable-dev-shm-usage")
options.binary_location = r"C:\Program Files\Config.exe"
driver = webdriver.Edge(service = service, options = options)
time.sleep(5)
driver.quit()
```
After running the above script, the WebView opens but nothing happens as expected and it closes after long time (looks like timeout).
I see the following error message in console :
![175956177-b674320f-ea45-4c81-a91e-e9b773367d60](https://user-images.githubusercontent.com/108277976/176169035-2fd6d8ec-8f40-4a52-aa6d-a80b28f5d13f.png)

Would you please help here.

**Comment by bwalderman** [comment]
You can find some help on using WebDriver with WebView2 at https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

The script above is missing `options.use_webview = True` which is necessary for Edge WebDriver to launch a WebView2-based app. Without that option, Edge WebDriver is attempting to launch Config.exe as if it were a browser.

Also please note that `add_argument` works differently when launching a WebView2 app vs. launching the Edge browser. Any arguments added here are passed to your WebView2 app (e.g. Config.exe) instead of the underlying WebView2 runtime, so unless Config.exe is somehow forwarding those arguments to the WebView2 runtime, then they will be ignored. To pass arguments to the WebView2 runtime, you will need to use the `webviewOptions` option. You can read more about that at https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options#edgeoptions-object

**Comment by bwalderman** [comment]
Closing this issue since the correct information should be available in the linked docs. Feel free to reopen this issue if the docs are unclear.
