### ISSUE TITLE
Last Windows 64 Stable API

### ISSUE THREAD

**Issue by stevensmith01** [MicrosoftEdge/EdgeWebDriver#39]
Is there an API to get the latest stable windows version of Microsoft Edge? The current API appears to give Linux and Mac versions but there isn't always a Win version associated. The web driver download page appears to be broken as well. So I am trying to read the API to make sure I download the latest version of the windows Web driver for my users.

**Comment by stevensmith01** [comment]
https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/LATEST_STABLE

I couldn't find any published list of endpoints. So I started to use this but I have found that the version returned here doesn't always mean there is a matching windows version in the repository.

**Comment by stevensmith01** [comment]
This endpoint returns 103.0.1264.51 today. When I go to the full directory, it only shows a mac and Linux driver for this version.![image](https://user-images.githubusercontent.com/11327549/178368188-12247902-d88b-4391-be14-8645620849d6.jpeg)

**Comment by bwalderman** [comment]
Hi @stevensmith01, as you found, the LATEST_STABLE endpoint isn't reliable because it doesn't always point to a Windows release. It only points to the latest stable channel release on any platform, whatever that happens to be.

The most reliable method to download Edge WebDriver would be to find your currently installed Edge browser version first. How to get the version information for a windows executable will depend on what language you are using. Once you have this information, you can download the exact matching driver using a URL such as https://msedgedriver.azureedge.net/103.0.1264.44/edgedriver_win64.zip. Substitute the version string with the Edge browser version.

If for some reason that fails, there are platform-specific endpoints you can use instead. First you need to know the major version of the Edge browser that is currently installed, e.g. 103. Then, use one of the following URLs, substituting the version number for your current Edge version:

https://msedgedriver.azureedge.net/LATEST_RELEASE_103_WINDOWS
https://msedgedriver.azureedge.net/LATEST_RELEASE_103_MACOS
https://msedgedriver.azureedge.net/LATEST_RELEASE_103_LINUX

You may also be interested in a tool like [WebDriverManager](https://bonigarcia.dev/webdrivermanager/) that automates this process for all major browsers, including Edge.
