### ISSUE TITLE
Add service_log_path option

### ISSUE THREAD

**Issue by JiveyGuy** [MicrosoftEdge/EdgeWebDriver#94]
When using a global logger (bad practice, I know) there is a flood of messages from EdgeWebDriver and its dependencies. 

The workaround with the Chrome driver was to do this:
```python
edge_driver = webdriver.Edge(options=options, service_log_path=os.path.devnull)
```

Request:

- Add logging configuration or disabling 
    - Would be nice if it affected requests and connection pool too. 

AB#45393643

**Comment by bwalderman** [comment]
Thanks for the feedback. We've heard a couple requests about making the log output easier to filter. I've added this to our internal backlog for investigation.

**Comment by bwalderman** [comment]
@JiveyGuy, the latest Selenium 4 Python release doesn't seem to support `service_log_path` as a constructor param to `webdriver.Edge` or `webdriver.Chrome` anymore. You can create a service and set its log path using `log_output` in the constructor, then pass that service to your `webdriver.Edge` object.

Source of Edge driver class:
https://github.com/SeleniumHQ/selenium/blob/6620bce4e8e9da1fee3ec5a5547afa7dece3f80e/py/selenium/webdriver/edge/webdriver.py

Since this is feedback about Selenium's API and not a feature of Edge WebDriver, I'd recommend opening an issue in the Selenium repo for further help.
